# Everything in this section will be available as an environment variable
https://docs.streamlit.io/streamlit-community-cloud/deploy-your-app/secrets-management
db_username = "Jane" <--- Anna Login Data to Streamlit
db_password = "12345qwerty"