<<<<<<< HEAD
db_username = "team1307"
db_password = "lewagon-team-runs-bvg-t1cket-control-bankrupt-th1s-1s-the-3nd"
=======
# Everything in this section will be available as an environment variable
https://docs.streamlit.io/streamlit-community-cloud/deploy-your-app/secrets-management
db_username = "Jane" <--- Anna Login Data to Streamlit
db_password = "12345qwerty"
>>>>>>> master
