# Dictionary of Berliner Bezirke
# scraped from Wikipedia, see bezirke_areas_dict_draft.ipynb
# Adjusted to our data["areas"]

bezirke = {
    "Charlottenburg-Wilmersdorf": [
        "Charlottenburg",
        "Wilmersdorf",
        "Schmargendorf",
        "Grunewald",
        "Westend",
        "Charlottenburg-Nord",
        "Halensee",
    ],
    "Friedrichshain-Kreuzberg": ["Friedrichshain", "Kreuzberg"],
    "Lichtenberg": [
        "Friedrichsfelde",
        "Karlshorst",
        "Lichtenberg",
        "Falkenberg",
        "Malchow",
        "Wartenberg",
        "Neu-Hohenschönhausen",
        "Alt-Hohenschönhausen",
        "Fennpfuhl",
        "Rummelsburg",
    ],
    "Marzahn-Hellersdorf": [
        "Marzahn",
        "Biesdorf",
        "Kaulsdorf",
        "Mahlsdorf",
        "Hellersdorf",
        "Berlin-Marzahn",
    ],
    "Mitte": [
        "Mitte",
        "Moabit",
        "Hansaviertel",
        "Tiergarten",
        "Wedding",
        "Gesundbrunnen",
    ],
    "Neukölln": ["Neukölln", "Britz", "Buckow", "Rudow", "Gropiusstadt"],
    "Pankow": [
        "Prenzlauer Berg",
        "PrenzlauerBerg",
        "Weißensee",
        "Blankenburg",
        "Heinersdorf",
        "Karow",
        "Stadtrandsiedlung Malchow",
        "Pankow",
        "Blankenfelde",
        "Buch",
        "Französisch Buchholz",
        "Niederschönhausen",
        "Rosenthal",
        "Wilhelmsruh",
    ],
    "Reinickendorf": [
        "Reinickendorf",
        "Tegel",
        "Konradshöhe",
        "Heiligensee",
        "Frohnau",
        "Hermsdorf",
        "Waidmannslust",
        "Lübars",
        "Wittenau",
        "Märkisches Viertel",
        "Borsigwalde",
    ],
    "Spandau": [
        "Spandau",
        "Haselhorst",
        "Siemensstadt",
        "Staaken",
        "Gatow",
        "Kladow",
        "Hakenfelde",
        "Falkenhagener Feld",
        "Wilhelmstadt",
    ],
    "Steglitz-Zehlendorf": [
        "Steglitz",
        "Lichterfelde",
        "Lankwitz",
        "Zehlendorf",
        "Dahlem",
        "Nikolassee",
        "Wannsee",
        "Schlachtensee",
    ],
    "Tempelhof-Schöneberg": [
        "Schöneberg",
        "Friedenau",
        "Tempelhof",
        "Mariendorf",
        "Marienfelde",
        "Lichtenrade",
    ],
    "Treptow-Köpenick": [
        "Alt-Treptow",
        "Plänterwald",
        "Baumschulenweg",
        "Johannisthal",
        "Niederschöneweide",
        "Altglienicke",
        "Adlershof",
        "Bohnsdorf",
        "Oberschöneweide",
        "Köpenick",
        "Friedrichshagen",
        "Rahnsdorf",
        "Grünau",
        "Müggelheim",
        "Schmöckwitz",
    ],
    "Brandenburg": [],
}
